import { Routes } from '@angular/router';
import { Index1Component } from "./pages/index1/index1.component";
import { Index2Component } from "./pages/index2/index2.component";
import { Index3Component } from "./pages/index3/index3.component";
import { Index4Component } from "./pages/index4/index4.component";
import { Index5Component } from "./pages/index5/index5.component";
import { Index6Component } from "./pages/index6/index6.component";
import { Index7Component } from "./pages/index7/index7.component";
import { Index8Component } from "./pages/index8/index8.component";
import { Index9Component } from "./pages/index9/index9.component";
import { Index10Component } from "./pages/index10/index10.component";
import { Index11Component } from "./pages/index11/index11.component";
import { Index12Component } from "./pages/index12/index12.component";
import { Index13Component } from "./pages/index13/index13.component";
import { Index14Component } from "./pages/index14/index14.component";
import { Index15Component } from "./pages/index15/index15.component";

export const routes: Routes = [
    { path: '', component: Index1Component },
    { path: 'index-2', component: Index2Component },
    { path: 'index-3', component: Index3Component },
    { path: 'index-4', component: Index4Component },
    { path: 'index-5', component: Index5Component },
    { path: 'index-6', component: Index6Component },
    { path: 'index-7', component: Index7Component },
    { path: 'index-8', component: Index8Component },
    { path: 'index-9', component: Index9Component },
    { path: 'index-10', component: Index10Component },
    { path: 'index-11', component: Index11Component },
    { path: 'index-12', component: Index12Component },
    { path: 'index-13', component: Index13Component },
    { path: 'index-14', component: Index14Component },
    { path: 'index-15', component: Index15Component },
];
